### ISSUE TITLE
Cookie Consent

### ISSUE THREAD

**Issue by arlogilbert** [erichard/awesome-gdpr#11]
Hi Eric,

Great list. We just discovered this and I'm grateful that you've listed our application (cookie consent aka https://cookieconsent.insites.com/ ) but about a year ago we renamed and relocated our application. We now offer a commercial version available here: https://www.osano.com/features/consent-management and the open source version is now located here: https://www.osano.com/cookieconsent

As well, we offer a DSAR form product now too :) https://www.osano.com/features/dsar-srr

If it's not too much trouble, would you consider updating your awesome list?

**Comment by erichard** [comment]
Hi Arlo,

I updated the list and added a DSAR section. 

Happy to see cookieConsent evolve to a full solution. I'll take a look someday ;)

Cheers
