### ISSUE TITLE
Cookie Consent Insites

### ISSUE THREAD

**Issue by Pixney-William** [erichard/awesome-gdpr#5]
Is this really compliant with gdpr, since you are not able to set the cookies you want to accept and not be able to go back to settings after you have accepted them.

Not asking because i think you are wrong to list it. I myself is just a little bit unsure if its enough and would like your thoughts on the matter. :)

**Comment by erichard** [comment]
You can use the opt-in feature which is compliant with the GDPR. But for a full compliance we also need to handle third party cookies and store consent. So you may want a complete solution like [CookieBot](https://www.cookiebot.com/en/).

**Comment by MatheusRV** [comment]
No opensource solutions for this?
